sudo: false
language: python
python: 3.6
branches:
  only:
    - master
    - develop

install:
  - pip install tox

script:
  # Make Python 3.5 available.
  - pyenv shell 2.7:3.5:3.6
  - tox -e py27,py35,py36,checkqa,coverage,coverage-py27
  - make test_integration
