sudo: false
language: python
python: 3.6
branches:
  only:
    - master
    - develop

env:
  global:
    - PYTEST_ADDOPTS='-vv --tb=auto --showlocals'

matrix:
  include:
    - env: TOXENV=py36-codecov,py36-integration-codecov,checkqa
      python: 3.6
    - env: TOXENV=py35-codecov,py35-integration-codecov
      python: 3.5
    - env: TOXENV=py34-codecov,py34-integration-codecov
      python: 3.4
    - env: TOXENV=py33-codecov,py33-integration-codecov
      python: 3.3
    - env: TOXENV=py27-codecov,py27-integration-codecov
      python: 2.7

install:
  - pip install codecov tox

script:
  - pyenv versions
  # Make Python 3.5 available (with python: 3.6).
  - |
    if [ "$TRAVIS_PYTHON_VERSION" = 3.6 ]; then
      pyenv shell 2.7:3.5:3.6
    fi
  - tox

after_success:
  - |
    set -x
    for c in $(find .tox/py* -name 'codecov-coverage.*'); do
      prof_name=${c##*/codecov-coverage.}
      prof_name=${prof_name%-codecov}
      prof_flags=${prof_name//-/ }
      COVERAGE_FILE="$c" coverage xml
      travis_retry codecov --required -X search gcov pycov -f coverage.xml --flags $prof_flags
      COVERAGE_FILE="$c" coverage report -m
    done

    if [ "$TRAVIS_PYTHON_VERSION" = 3.6 ]; then
      echo "Uploading Python 3.6 coverage to coveralls..."
      coverage combine .tox/py36-integration-codecov/tmp/codecov-coverage* \
        .tox/py36-codecov/tmp/codecov-coverage*
      pip install coveralls
      coveralls
      coverage report -m
    fi
    set +x
